### ISSUE TITLE
Main - SOS

### ISSUE THREAD

**Issue by jamypurfic** [SLG-2022-G3/HELP#12]
- [x] Creation of home fragment
- [x] creation of contacts fragment
- [x] creation of profile fragment
- [ ] #25
- [x] Red blinking SOS button in Home fragment
- [x] Bottom navigation

**Comment by SAM4you** [comment]
We have no Settings Screen in our Wireframes

**Comment by jamypurfic** [comment]
@SAM4you thanks... I will open a new issue for the settings screen and remind @Balthazar-02 to layout a wireframe for it
